package cmd

import (
	"context"
	"fmt"
	"strings"

	"github.com/1broseidon/ketch/config"
	"github.com/spf13/cobra"
)

// Anvil · target: cmd/ · kind: cli · boundary: tool
// callers: agent,script,human-operator · risk: R0+R1 (root -b dropped; search -b added)
// contracts: see CHANGELOG.md · obligations: json,version,help

// cfg is loaded at init so subcommand flag defaults can reference it. A bad
// KETCH_* env value must not crash unrelated commands (`ketch version`), so
// the load error is held in cfgErr and surfaced from PersistentPreRunE only
// for commands that actually consume config; cfg stays best-effort usable
// (invalid env vars skipped) for flag-default display in the meantime.
var cfgResult, cfgErr = config.Load()
var cfg = cfgResult.Config

var rootCmd = &cobra.Command{
	Use:   "ketch",
	Short: "Fast web search and scrape for agents",
	Long:  `ketch is a blazing fast CLI for agentic search and scrape workflows. Search the web, scrape pages to clean markdown, or do both in one shot.`,
	PersistentPreRunE: func(cmd *cobra.Command, _ []string) error {
		prepareUpdateNotice(cmd)
		if cfgErr != nil && commandUsesConfig(cmd) {
			return exitErrf(ExitValidation, "invalid configuration:\n%v", cfgErr)
		}
		return nil
	},
	PersistentPostRun: func(cmd *cobra.Command, _ []string) {
		emitUpdateNotice(cmd)
	},
	RunE:         runRoot,
	SilenceUsage: true,
}

func Execute() error {
	return rootCmd.Execute()
}

// ExecuteContext runs the root command with a caller-supplied context.
// main.go passes a context that cancels on SIGINT/SIGTERM so foreground
// commands (notably crawl) can shut down gracefully.
func ExecuteContext(ctx context.Context) error {
	return rootCmd.ExecuteContext(ctx)
}

func init() {
	rootCmd.PersistentFlags().Bool("json", false, "output as JSON")
	// `--backend` is owned by each search-style subcommand (search, code, docs)
	// rather than the root so non-search subcommands (scrape, crawl, cache,
	// browser, config) don't advertise an inert global flag, and so the three
	// independent backend universes never collide on one persistent `-b`.
}

// commandUsesConfig reports whether cmd reads the effective config, i.e.
// whether a KETCH_* env parse error should block it. version/help/completion
// never touch config; `config init/set/path` operate on the file only (via
// config.LoadFile), so they too keep working under a broken environment.
func commandUsesConfig(cmd *cobra.Command) bool {
	switch cmd.Name() {
	case "version", "help", "completion":
		return false
	case "init", "set", "path":
		if cmd.Parent() != nil && cmd.Parent().Name() == "config" {
			return false
		}
	}
	// Shell completion subcommands (completion bash/zsh/...) are generated by
	// cobra with the shell name, so match on the parent too.
	if cmd.Parent() != nil && cmd.Parent().Name() == "completion" {
		return false
	}
	return true
}

func runRoot(cmd *cobra.Command, _ []string) error {
	// Print a compact, generated summary — derived entirely from the live
	// command tree and config backend lists so it can never drift.
	w := cmd.OutOrStdout()
	p := func(format string, a ...any) { fmt.Fprintf(w, format, a...) } //nolint:errcheck

	p("ketch — web search, code search, docs, and scrape in one binary.\n\n")

	p("Commands:\n")
	// Surface-first ordering: main research commands first, then supporting ones.
	order := []string{"search", "code", "docs", "scrape", "crawl", "browser", "cache", "config", "doctor"}
	byName := make(map[string]*cobra.Command, len(cmd.Commands()))
	for _, sub := range cmd.Commands() {
		byName[sub.Name()] = sub
	}
	seen := make(map[string]bool)
	for _, name := range order {
		if sub, ok := byName[name]; ok {
			p("  %-10s  %s\n", sub.Name(), sub.Short)
			seen[name] = true
		}
	}
	// Any commands added later that aren't in the priority list appear at the end.
	for _, sub := range cmd.Commands() {
		if !seen[sub.Name()] && sub.Name() != "help" && sub.Name() != "completion" {
			p("  %-10s  %s\n", sub.Name(), sub.Short)
		}
	}

	p("\nBackends:\n")
	p("  %-10s  %s\n", "search", joinWithDefault(config.SelectableBackends(), cfg.Backend))
	p("  %-10s  %s\n", "code", joinWithDefault(config.AvailableCodeBackends(), cfg.CodeBackend))
	p("  %-10s  %s\n", "docs", joinWithDefault(config.AvailableDocBackends(), cfg.DocsBackend))

	p("\nRun 'ketch <command> --help' for flags and examples.\n")
	return nil
}

// joinWithDefault formats a backend list, marking the active one with "(default)".
func joinWithDefault(backends []string, active string) string {
	out := make([]string, len(backends))
	for i, b := range backends {
		if b == active {
			out[i] = b + " (default)"
		} else {
			out[i] = b
		}
	}
	return strings.Join(out, ", ")
}
